default: switch

[linux]
switch flags="": git-add
    sudo nixos-rebuild switch --flake . --impure {{flags}}

[macos]
switch flags="": git-add
    nix run -- nix-darwin switch --flake . {{flags}}

trace: (switch "--show-trace")
    
home: git-add
    nix run -- home-manager switch --flake $HOME/.dotfiles#$(hostname)

update: git-add
    nix flake update

git-add:
    git -C $HOME/.dotfiles add --intent-to-add --all
